version: "3.8"

services:
  bot:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./events.db:/app/events.db
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
